language: python
python:
  - "2.6"
  - "2.7"
  - "2.7.10"
  - "3.2"
  - "3.3"
  - "3.4"

install:
- pip install .  
- pip install selenium
- pip install -r requirements.txt

script: python travis_sample.py