language: python

install: 
- pip install selenium pytest pytest-xdist

script: py.test --boxed -n5 travis_sample.py

env:
  global:
    - secure: s61/9s5RCgG9kECdKX89G9ko7ND+sbDUU8iZh9bLQOVFtYNc4nw44v++neIw41Cqno3V49AFfiw7wMANwlzl59zW0oXOpoLf9zfVY704ZttTicfgszZuGO4dRimPYyvAvi9p6yYQdGLCxLzK1qqSvyeVw+6XJi62Oah5pJd4oco9p3BdoMekCh0TWlCPDdsr9lV4YYOW20NsY+1HK3ivp8ysyBgt00sIzE/7m8klwYBj9C6MYDGFFVsBiG6xix915NXJsZbJ/kvzdnBNWsqdzkZLzSwGJvk362cPAme+XVqWDgWp7/99OdEru8cMpdRvnogjLuLYsgv8brDPpzAbvwsIynR2HxGLzKOAYqS20bSjmrR3FWuVZvHgZUOASldfVhTyOyHHiaFjXDmOSSgzBe5QzMpD7qZx08Mc0Qm1J4ruABNmENjQCnJfktVuYmnLBotAFSBUh0brpIPnqIrQ2u9Dudt9oeVv1QaSBZhfKDYner4v9KT7SeeEqkirryRKC4pTGgkQJW9Gdh9TBvezk3ojnI8cNY6l64TFFnpXz1VhKvXnBK/HMvVqfhx5g2351Glt4ZFWPHuaweb3hYM83L7dKcUT/NygmhY2nFDODFEKvtV3BwZ0cFPABI/fMHhLqEdNrXz9Ht8SkBJ60QEKc3xJOyFJ4c6mxeNly/xYxJw=
    - secure: 3Y0q6CnPbjsi4h9DpetEYwQbUiWlT3G6p8X0AB4n+T7i8s7UcJxkLRvmV4yRW/Gih4LpszHcV6CPL3PPShp3ffjlOcBvh163w7oUoPB7//qRlXwNdvKpgExjetkytKGH/DbZVZNU4YmpBhG+nat6ivwhir4BkftLalNSaJHNku77dsawt6AQ4EAtSu1tW3/ZwMPa+xQHCheswNZPX4Q//KglT0KcL6WSnkVeEdAkQTF9G/dbDa5sT/X56r+2D5przcyWzYBTvD7NtVetKsNdUVO6+TdjvF+gO6cbsd5l3squk9hjbH4PW9WvV0m+TIHBW4qyZRrptbUDMmcjHB7+Sx7VPH6FCbjryK5U9hsaIfU5dJp1Xl67iu2fcvMzv4reWC1/VdXTnLx3K3YdxFvYf1zetv7YynQukoGCFomKCC8kiJ7FdIUwDLggLKun2/JyavP1vVYMXTpk2HxTDw/7Bl+kT+C9lZ6o+FOvKawcLfWZYjT02cndHBgNhqzAEtCWPuM6iMvbJBken+r55qqfBDy4IRc1MyVW8ym4QzCL0dcSGfkzL+XiSoM1jhUIv/5DBG1unf3hLBPeff4TtDQD4zjKKNMq/NnEqIuht2XeEn/Eqj24X2i5nLA9N5Da5Dr8PiwU2bmtDnFfThuE2iClbdBMYa6kOXZyh59GRx7zuwA=

addons:
  sauce_connect: true
